<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5VGUJVE" failures="1" tests="5" name="Default test" time="1.601" errors="0" timestamp="2023-04-29T03:47:49 PDT">
  <testcase classname="StoreProcedureTesting.SPTesting" name="test_storedProcedureExists" time="0.273"/>
  <testcase classname="StoreProcedureTesting.SPTesting" name="test_SelectAllCustomers" time="0.208"/>
  <testcase classname="StoreProcedureTesting.SPTesting" name="test_SelectAllCustomersByCity" time="0.042"/>
  <testcase classname="StoreProcedureTesting.SPTesting" name="test_SelectAllCustomersByCityAndPincode" time="0.026"/>
  <testcase classname="StoreProcedureTesting.SPTesting" name="test_get_order_by_cust" time="0.033">
    <failure type="java.sql.SQLException" message="Parameter number 2 is not an OUT parameter">
      <![CDATA[java.sql.SQLException: Parameter number 2 is not an OUT parameter
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
at com.mysql.cj.jdbc.CallableStatement.checkIsOutputParam(CallableStatement.java:645)
at com.mysql.cj.jdbc.CallableStatement.registerOutParameter(CallableStatement.java:1717)
at com.mysql.cj.jdbc.CallableStatement.registerOutParameter(CallableStatement.java:1725)
at StoreProcedureTesting.SPTesting.test_get_order_by_cust(SPTesting.java:122)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_get_order_by_cust -->
</testsuite> <!-- Default test -->
